language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"

install:
  - pip install requests
  - pip install httpretty
  - pip install coverage
  - pip install coveralls
  - python setup.py install

script:
  - nosetests --with-coverage agms/test/unit/*

after_success:
  - coveralls